### ISSUE TITLE
Feature Request: Execute a "goto line" action on selection of error/warning

### ISSUE THREAD

**Issue by nmaludy** [tam17aki/helm-flymake#2]
Hello,

I have a feature request for you.

It would be great if helm-flymake would change move point to the warning/error line when selecting a specific warning/error (i usually use enter after finding the warning/error i want). 

As a "nice to have" reach feature. It would be even better if helm-flymake behaved like helm-swoop, where point is automatically moved to the selected line based on the info in the helm window.

Thanks,
Nick

**Comment by tam17aki** [comment]
Merged. Thanks.
